version = 0.1
[default.deploy.parameters]
stack_name = "aws-lambda-to-lambda-with-sam"
resolve_s3 = false
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
s3_prefix = "aws-lambda-to-lambda-with-sam"

